//
//  EditGeneralRateSettingViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 11/1/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

protocol RateSettingDelegate: class {
    func updateDataRateSettingList()
}

class EditGeneralRateSettingViewController: BaseViewController {
    
    @IBOutlet weak var roomTypeView: AppTextFieldLogo!
    @IBOutlet weak var bedNumView: AppTextFieldLogo!
    @IBOutlet weak var customerNumView: AppTextFieldLogo!

	var presenter: EditGeneralRateSettingPresenterProtocol?
    
    var rateSetting: RateSettingEntity?
    
    weak var delegate: RateSettingDelegate?

	override func viewDidLoad() {
        super.viewDidLoad()
        self.definesPresentationContext = true
        self.view.backgroundColor = AppColor.normalBlack.withAlphaComponent(0.3)
        setData()
    }

    override func setUpViews() {
        roomTypeView.setTitleAndLogo(AppImage.imgRoom, title: "Loại phòng")
        bedNumView.setTitleAndLogo(AppImage.coupleRoom, title: "Số giường")
        customerNumView.setTitleAndLogo(AppImage.imgUser, title: "Số người")
    }
    
    func setData() {
        guard let data = rateSetting else { return }
        if let room = data.RoomClass {
            roomTypeView.setText(room.Name)
            bedNumView.setText("\(room.NumBed*)")
            customerNumView.setText("\(room.NumCustomer*)")
        }
    }
    
    func getData() -> RateSettingEntity? {
        rateSetting?.RoomClass?.Name = roomTypeView.getText()&
        rateSetting?.RoomClass?.NumBed = Int(bedNumView.getText()&)*
        rateSetting?.RoomClass?.NumCustomer = Int(customerNumView.getText()&)*
        return rateSetting
    }
    
    @IBAction func updateButtonTapped() {
        guard let param = getData() else { return }
        presenter?.addRoomClass(param: param)
    }
    
    @IBAction func cancelButtonTapped() {
        self.closePage()
    }
}

extension EditGeneralRateSettingViewController: EditGeneralRateSettingViewProtocol {
    func didAddRoomClass(result: [RateSettingEntity]?, error: APIError?) {
        if let _ = result {
            self.delegate?.updateDataRateSettingList()
            self.closePage()
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }
}
