//
//  EditGeneralRateSettingPresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 11/1/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class EditGeneralRateSettingPresenter: EditGeneralRateSettingPresenterProtocol {
    
    func addRoomClass(param: RateSettingEntity) {
        interactor?.addRoomClass(param: param)
    }
    

    weak private var view: EditGeneralRateSettingViewProtocol?
    var interactor: EditGeneralRateSettingInteractorInputProtocol?
    private let router: EditGeneralRateSettingWireframeProtocol

    init(interface: EditGeneralRateSettingViewProtocol,
         interactor: EditGeneralRateSettingInteractorInputProtocol?,
         router: EditGeneralRateSettingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension EditGeneralRateSettingPresenter: EditGeneralRateSettingInteractorOutputProtocol {
    func didAddRoomClass(result: [RateSettingEntity]?, error: APIError?) {
        view?.didAddRoomClass(result: result, error: error)
    }
}
