//
//  ServiceManagementRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 8/23/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ServiceManagementRouter: ServiceManagementWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ServiceManagementViewController(nibName: nil, bundle: nil)
        let interactor = ServiceManagementInteractor()
        let router = ServiceManagementRouter()
        let presenter = ServiceManagementPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
