//
//  CheckInViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CheckInViewController: BaseViewController {

    @IBOutlet weak var tfCustomerName       : AppTextFieldLogo!
    @IBOutlet weak var tfIndentifierNumber  : AppTextFieldLogo!
    @IBOutlet weak var tfIndentifierDate    : TextFieldCalendar!
    @IBOutlet weak var tfAdress             : AppTextFieldLogo!
    @IBOutlet weak var tfCheckInTime        : TextFieldCalendar!
    @IBOutlet weak var vTimeType            : AppDropdown!
    @IBOutlet weak var vConfigurePrice      : AppDropdown!
    @IBOutlet weak var vService             : ServiceView!
    @IBOutlet weak var tvNote               : AppTextViewLogo!

	var presenter: CheckInPresenterProtocol?

    var listPrice: [ConfigPriceEntity] = [] {
        didSet {
            self.vConfigurePrice.dataSource = self.listPrice.map({$0.Name&})
        }
    }

    var room: RoomEntity?

	override func viewDidLoad() {
        super.viewDidLoad()
        getData()
    }

    private func getData() {
        guard let room = room, let roomId = room.Id else { return }
        presenter?.getConfigPrice(roomId: roomId)
    }

    override func setUpNavigation() {
        setTitleNavigation(title: "Nhận phòng")
        addBackWhiteToNavigation()
        addButtonTextToNavigation(title: "Nhận", style: .right, action: #selector(btnAcceptTapped))
    }

    override func setUpViews() {
        tfCustomerName.setTitleAndLogo(AppImage.imgUser, title: "Khách hàng")
        tfIndentifierNumber.setTitleAndLogo(AppImage.imgReceipts, title: "CMT")
        tfAdress.setTitleAndLogo(AppImage.imgAddress, title: "Địa chỉ")

        vTimeType.setTitleAndLogo(AppImage.imgTime, title: "Tính theo")
        vConfigurePrice.setTitleAndLogo(AppImage.imgPrice, title: "Cấu hình giá")
//        vService.setTitleAndLogo(AppImage.imgPayment, title: "Dịch vụ")
        tfIndentifierDate.setTitleAndLogo(AppImage.imgTime, title: "Ngày cấp")
        tfIndentifierDate.setTitleAndLogo(AppImage.imgTime, title: "Thời gian")

        tvNote.setTitleAndLogo(AppImage.imgNote, title: "Ghi chú")
        vTimeType.dataSource = ["Theo giờ", "Theo ngày", "Qua đêm", "Theo tháng"]

    }

    @objc func btnAcceptTapped() {

    }

}

extension CheckInViewController: CheckInViewProtocol {
    func didGetConfigPrice(result: [ConfigPriceEntity]?, error: APIError?) {
        if let result = result {
            self.listPrice = result
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }

	
}
