//
//  AddRateSettingViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

enum GeneralInfo: Int, CaseIterable {
    case roomType
    case bedNum
    case customerNum
    case priceByDay
    case priceByNight
    case priceByMonth
}

class AddRateSettingViewController: BaseViewController {
    
    @IBOutlet weak var tableView: UITableView!

	var presenter: AddRateSettingPresenterProtocol?
    
    let param = RateSettingEntity()
    
    weak var delegate: RateSettingDelegate?

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
    }
    
    override func setUpNavigation() {
        setTitleNavigation(title: "Thêm mới loại phòng")
        addBackWhiteToNavigation()
    }

    private func configureTableView() {
        tableView.registerTableCell(GeneralInfoCell.self)
        tableView.dataSource = self
        tableView.delegate = self
        tableView.rowHeight = UITableView.automaticDimension
    }
    
    @IBAction func nextButtonTapped() {
        let vc = AddSurchargeRouter.createModule(param: param, type: .AddRoom)
        vc.delegate = self
        self.push(controller: vc)
    }
}

extension AddRateSettingViewController: AddRateSettingViewProtocol {
	
}

extension AddRateSettingViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return GeneralInfo.allCases.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(GeneralInfoCell.self)
        cell.setData(index: indexPath.row)
        cell.textfieldDidChangeCallback = {[weak self] text in
            guard let self = self else { return }
            self.setParam(index: indexPath.row, text: text)
        }
        return cell
    }
    
    private func setParam(index: Int, text: String) {
        switch index {
        case GeneralInfo.roomType.rawValue:
            param.RoomClass?.Name = text
        case GeneralInfo.bedNum.rawValue:
            param.RoomClass?.NumBed = Int(text)
        case GeneralInfo.customerNum.rawValue:
            param.RoomClass?.NumCustomer = Int(text)
        case GeneralInfo.priceByDay.rawValue:
            param.ConfigPrices.first?.ConfigPriceRow?.PriceByDay = Int(text)
        case GeneralInfo.priceByNight.rawValue:
            param.ConfigPrices.first?.ConfigPriceRow?.PriceByNight = Int(text)
        case GeneralInfo.priceByMonth.rawValue:
            param.ConfigPrices.first?.ConfigPriceRow?.PriceByMonth = Int(text)
        default:
            break
        }
    }
}

extension AddRateSettingViewController: UITableViewDelegate {
    
}

extension AddRateSettingViewController: RateSettingDelegate {
    func updateDataRateSettingList() {
        delegate?.updateDataRateSettingList()
    }
}
