//
//  AddRateSettingViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

enum GeneralInfo: Int, CaseIterable {
    case roomType
    case bedNum
    case customerNum
    case priceByDay
    case priceByNight
    case priceByMonth
}

class AddRateSettingViewController: BaseViewController {
    
    @IBOutlet weak var tableView: UITableView!

	var presenter: AddRateSettingPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
    }
    
    override func setUpNavigation() {
        setTitleNavigation(title: "Thêm mới loại phòng")
        addBackWhiteToNavigation()
    }

    private func configureTableView() {
        tableView.registerTableCell(GeneralInfoCell.self)
        tableView.dataSource = self
        tableView.delegate = self
        tableView.rowHeight = UITableView.automaticDimension
    }
    
    @IBAction func nextButtonTapped() {
        let vc = AddSurchargeRouter.createModule()
        self.push(controller: vc)
    }
}

extension AddRateSettingViewController: AddRateSettingViewProtocol {
	
}

extension AddRateSettingViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return GeneralInfo.allCases.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(GeneralInfoCell.self)
        cell.setData(index: indexPath.row)
        return cell
    }
    
    
}

extension AddRateSettingViewController: UITableViewDelegate {
    
}
