//
//  EditGeneralRateSettingProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 11/1/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol EditGeneralRateSettingWireframeProtocol: class {

}
//MARK: Presenter -
protocol EditGeneralRateSettingPresenterProtocol: class {

    var interactor: EditGeneralRateSettingInteractorInputProtocol? { get set }
    func addRoomClass(param: RateSettingEntity)
}

//MARK: Interactor -
protocol EditGeneralRateSettingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didAddRoomClass(result: [RateSettingEntity]?, error: APIError?)
}

protocol EditGeneralRateSettingInteractorInputProtocol: class {

    var presenter: EditGeneralRateSettingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func addRoomClass(param: RateSettingEntity)
}

//MARK: View -
protocol EditGeneralRateSettingViewProtocol: class {

    var presenter: EditGeneralRateSettingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didAddRoomClass(result: [RateSettingEntity]?, error: APIError?)
}
