//
//  LoginPresenter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/22/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class LoginPresenter: LoginPresenterProtocol {
    func login(userName: String, password: String) {
        interactor?.login(userName: userName, password: password)
    }


    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorInputProtocol?
    private let router: LoginWireframeProtocol

    init(interface: LoginViewProtocol, interactor: LoginInteractorInputProtocol?, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension LoginPresenter: LoginInteractorOutputProtocol {
    func didLogin(result: UserEntity?, error: APIError?) {
        view?.didLogin(result: result, error: error)
    }

	
}
