//
//  InsertPopUpViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/27/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

enum FloorAndRoomAction {
    case editFloor
    case addFloor
    case editRoom
    case addRoom
}

protocol InsertPopUpViewControllerDelegate: class {
    func acceptTapped(action: FloorAndRoomAction, floorParam: InsertOrUpdateFloorParam?, roomParam: EditRoomParam?)
}

class InsertPopUpViewController: BaseViewController {
    
    @IBOutlet weak var tfName   : AppTextFieldLogo!
    @IBOutlet weak var vFloor   : AppDropdown!
    @IBOutlet weak var vRoomType: AppDropdown!

	var presenter: InsertPopUpPresenterProtocol?
    
    var actionType: FloorAndRoomAction!
    
    var floor: FloorEntity?
    var room: RoomEntity?
    var indexPath: IndexPath!
    
    let floorParam = InsertOrUpdateFloorParam()
    let roomParam = EditRoomParam()
    
    weak var delegate: InsertPopUpViewControllerDelegate?

	override func viewDidLoad() {
        super.viewDidLoad()
        self.definesPresentationContext = true
        self.view.backgroundColor = AppColor.normalBlack.withAlphaComponent(0.3)
    }
    
    @IBAction func btnCloseTapped() {
           self.dismiss(animated: false)
       }
    
    override func setUpViews() {
        vFloor.dataSource = ["Tang 1", "Tang 2", "tang 3"]
        vRoomType.dataSource = ["Phong don", "Phong doi"]
        
        vFloor.setTitleAndLogo(AppImage.imgHotel, title: "Thuộc tầng")
        vRoomType.setTitleAndLogo(AppImage.coupleRoom, title: "Loại phòng")
        
        switch actionType {
        case .editFloor, .addFloor:
            tfName.setTitleAndLogo(AppImage.imgRoom, title: "Tên tầng")
            vFloor.isHidden = true
            vRoomType.isHidden = true
            if actionType == .editFloor {
                self.tfName.setText(floor?.Name)
            }
        default:
            tfName.setTitleAndLogo(AppImage.imgRoom, title: "Tên phòng")
            vFloor.isHidden = false
            vRoomType.isHidden = false
            roomParam.RoomClassId = room?.RoomClassId
            roomParam.RoomId =  room?.Id
            
            if actionType == .editRoom {
                roomParam.FloorId = floor?.Id
                tfName.setText(room?.Name)
            }
        }
        
    }
    
    @IBAction func btnAcceptTapped() {
        switch actionType {
        case .addFloor:
            floorParam.Name = tfName.getText()
            delegate?.acceptTapped(action: actionType, floorParam: floorParam, roomParam: nil)
        case .editFloor:
            floorParam.Name = tfName.getText()
            floorParam.NumRooms = floor?.NumRooms
            floorParam.RoomClassId = floor?.RoomClassId
            floorParam.Id = floor?.Id
            delegate?.acceptTapped(action: actionType, floorParam: floorParam, roomParam: nil)
        default:
            roomParam.RoomName = tfName.getText()
            delegate?.acceptTapped(action: actionType, floorParam: nil, roomParam: roomParam)
        }
        
        btnCloseTapped()
    }

}

extension InsertPopUpViewController: InsertPopUpViewProtocol {
	
}
