//
//  InsertPopUpProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/27/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol InsertPopUpWireframeProtocol: class {

}
//MARK: Presenter -
protocol InsertPopUpPresenterProtocol: class {

    var interactor: InsertPopUpInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol InsertPopUpInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol InsertPopUpInteractorInputProtocol: class {

    var presenter: InsertPopUpInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol InsertPopUpViewProtocol: class {

    var presenter: InsertPopUpPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
