//
//  InsertPopUpInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/27/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class InsertPopUpInteractor: InsertPopUpInteractorInputProtocol {

    weak var presenter: InsertPopUpInteractorOutputProtocol?
}
