//
//  InsertPopUpPresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/27/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class InsertPopUpPresenter: InsertPopUpPresenterProtocol {

    weak private var view: InsertPopUpViewProtocol?
    var interactor: InsertPopUpInteractorInputProtocol?
    private let router: InsertPopUpWireframeProtocol

    init(interface: InsertPopUpViewProtocol, interactor: InsertPopUpInteractorInputProtocol?, router: InsertPopUpWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension InsertPopUpPresenter: InsertPopUpInteractorOutputProtocol {
	
}