//
//  InsertPopUpProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/27/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol InsertPopUpWireframeProtocol: class {

}
//MARK: Presenter -
protocol InsertPopUpPresenterProtocol: class {

    var interactor: InsertPopUpInteractorInputProtocol? { get set }
    
    func getListRoomClass()
    func getListFloor()
    func getRoomForEdit(roomID: Int)
}

//MARK: Interactor -
protocol InsertPopUpInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetListRoomClass(result: [RoomTypeEntity]?, error: APIError?)
    func didGetListFloor(result: [FloorEntity]?, error: APIError?)
    func didGetRoomForEdit(result: EditRoomParam?, error: APIError?)
}

protocol InsertPopUpInteractorInputProtocol: class {

    var presenter: InsertPopUpInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getListRoomClass()
    func getListFloor()
    func getRoomForEdit(roomID: Int)
}

//MARK: View -
protocol InsertPopUpViewProtocol: class {

    var presenter: InsertPopUpPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetListRoomClass(result: [RoomTypeEntity]?, error: APIError?)
    func didGetListFloor(result: [FloorEntity]?, error: APIError?)
    func didGetRoomForEdit(result: EditRoomParam?, error: APIError?)
}
