//
//  InsertPopUpPresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/27/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class InsertPopUpPresenter: InsertPopUpPresenterProtocol {
    func getRoomForEdit(roomID: Int) {
        interactor?.getRoomForEdit(roomID: roomID)
    }
    
    
    func getListFloor() {
        interactor?.getListFloor()
    }
    
    func getListRoomClass() {
        interactor?.getListRoomClass()
    }
    
    weak private var view: InsertPopUpViewProtocol?
    var interactor: InsertPopUpInteractorInputProtocol?
    private let router: InsertPopUpWireframeProtocol

    init(interface: InsertPopUpViewProtocol, interactor: InsertPopUpInteractorInputProtocol?, router: InsertPopUpWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension InsertPopUpPresenter: InsertPopUpInteractorOutputProtocol {
    func didGetRoomForEdit(result: EditRoomParam?, error: APIError?) {
        view?.didGetRoomForEdit(result: result, error: error)
    }
    
    
    func didGetListFloor(result: [FloorEntity]?, error: APIError?) {
        view?.didGetListFloor(result: result, error: error)
    }
    
    func didGetListRoomClass(result: [RoomTypeEntity]?, error: APIError?) {
        view?.didGetListRoomClass(result: result, error: error)
    }
	
}
