//
//  ListServiceProtocols.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 3/21/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol ListServiceWireframeProtocol: class {

}
//MARK: Presenter -
protocol ListServicePresenterProtocol: class {

    var interactor: ListServiceInteractorInputProtocol? { get set }

    func getWidget()
}

//MARK: Interactor -
protocol ListServiceInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetWidget(result: [WidgetTypeEntity]?, error: APIError?)
}

protocol ListServiceInteractorInputProtocol: class {

    var presenter: ListServiceInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getWidget()
}

//MARK: View -
protocol ListServiceViewProtocol: class {

    var presenter: ListServicePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetWidget(result: [WidgetTypeEntity]?, error: APIError?)
}
