//
//  ListServiceViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 3/21/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListServiceViewController: BaseViewController {

    @IBOutlet weak var tbListService: UITableView!

	var presenter: ListServicePresenterProtocol?

    var listWidgetType: [WidgetTypeEntity] = [] {
        didSet {
            self.tbListService.reloadData()
        }
    }

    var selectedCallback: ((_ widget: WidgetEntity) -> Void)?

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
        presenter?.getWidget()
    }

    override func setUpNavigation() {
        addBackWhiteToNavigation()
    }

    private func configureTableView() {
        tbListService.registerTableCell(ServiceCell.self)
        tbListService.delegate = self
        tbListService.dataSource = self
    }

}

extension ListServiceViewController: ListServiceViewProtocol {
    func didGetWidget(result: [WidgetTypeEntity]?, error: APIError?) {
        if let result = result {
            self.listWidgetType = result
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }
	
}

extension ListServiceViewController: UITableViewDelegate, UITableViewDataSource {

    func numberOfSections(in tableView: UITableView) -> Int {
        return listWidgetType.count
    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listWidgetType[section].Widgets.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(ServiceCell.self)
        cell.lbTitle.text = listWidgetType[indexPath.section].Widgets[indexPath.row].NamePrice
        return cell
    }

    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return listWidgetType[section].GroupName&
    }

    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 50
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        self.selectedCallback?(listWidgetType[indexPath.section].Widgets[indexPath.row])
        self.closePage()
    }
}
