//
//  ReceiptProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 6/15/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol ReceiptWireframeProtocol: class {

}
//MARK: Presenter -
protocol ReceiptPresenterProtocol: class {

    var interactor: ReceiptInteractorInputProtocol? { get set }
    func getInvoices(page: Int, pageSize: Int, invoiceType: [Int], isInDay: Bool)
}

//MARK: Interactor -
protocol ReceiptInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetInvoices(result: InvoiceResponse?, error: APIError?)
}

protocol ReceiptInteractorInputProtocol: class {

    var presenter: ReceiptInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getInvoices(page: Int, pageSize: Int, invoiceType: [Int], isInDay: Bool)
}

//MARK: View -
protocol ReceiptViewProtocol: class {

    var presenter: ReceiptPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetInvoices(result: InvoiceResponse?, error: APIError?)
}
