//
//  ListReceiptPresenter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListReceiptPresenter: ListReceiptPresenterProtocol {
    func getInvoices(page: Int, pageSize: Int, invoiceType: [Int], isInDay: Bool) {
        interactor?.getInvoices(page: page, pageSize: pageSize, invoiceType: invoiceType, isInDay: isInDay)
    }


    weak private var view: ListReceiptViewProtocol?
    var interactor: ListReceiptInteractorInputProtocol?
    private let router: ListReceiptWireframeProtocol

    init(interface: ListReceiptViewProtocol, interactor: ListReceiptInteractorInputProtocol?, router: ListReceiptWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension ListReceiptPresenter: ListReceiptInteractorOutputProtocol {
    func didGetInvoices(result: InvoiceResponse?, error: APIError?) {
        view?.didGetInvoices(result: result, error: error)
    }

	
}
