//
//  ListRoomProtocols.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/23/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol ListRoomWireframeProtocol: class {

}
//MARK: Presenter -
protocol ListRoomPresenterProtocol: class {

    var interactor: ListRoomInteractorInputProtocol? { get set }

    func getRoomsByClass()
    func changeStatusRoom(roomID: Int, status: String)
}

//MARK: Interactor -
protocol ListRoomInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetRoomsByClass(result: [RoomTypeEntity]?, error: APIError?)
    func didChangeStatusRoom(result: BaseResponse?, error: APIError?)
}

protocol ListRoomInteractorInputProtocol: class {

    var presenter: ListRoomInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getRoomsByClass()
    func changeStatusRoom(roomID: Int, status: String)
}

//MARK: View -
protocol ListRoomViewProtocol: class {

    var presenter: ListRoomPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetRoomsByClass(result: [RoomTypeEntity]?, error: APIError?)
    func didChangeStatusRoom(result: BaseResponse?, error: APIError?)
}
