//
//  EditServiceInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 19/03/2021.
//  Copyright © 2021 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class EditServiceInteractor: EditServiceInteractorInputProtocol {
    
    let service = Provider.shared.receptionistAPIService
    
    func addWidget(param: WidgetEntity) {
        service.addWidget(param: param) { (result) in
            self.presenter?.didAddWidget(result: result, error: nil)
        } failure: { (error) in
            self.presenter?.didAddWidget(result: nil, error: error)
        }
    }
    

    weak var presenter: EditServiceInteractorOutputProtocol?
}
