//
//  EditServiceProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 19/03/2021.
//  Copyright © 2021 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol EditServiceWireframeProtocol: class {

}
//MARK: Presenter -
protocol EditServicePresenterProtocol: class {

    var interactor: EditServiceInteractorInputProtocol? { get set }
    
    func addWidget(param: WidgetEntity)
}

//MARK: Interactor -
protocol EditServiceInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didAddWidget(result: [WidgetTypeEntity]?, error: APIError?)
}

protocol EditServiceInteractorInputProtocol: class {

    var presenter: EditServiceInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func addWidget(param: WidgetEntity)
}

//MARK: View -
protocol EditServiceViewProtocol: class {

    var presenter: EditServicePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didAddWidget(result: [WidgetTypeEntity]?, error: APIError?)
}
