//
//  EditServiceRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 19/03/2021.
//  Copyright © 2021 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class EditServiceRouter: EditServiceWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(listType: [WidgetTypeEntity], widget: WidgetEntity, indexType: Int) -> EditServiceViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = EditServiceViewController.initFromNib()
        let interactor = EditServiceInteractor()
        let router = EditServiceRouter()
        let presenter = EditServicePresenter(interface: view,
                                             interactor: interactor,
                                             router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view.indexType = indexType
        view.listType = listType
        view.widget = widget

        return view
    }
    
    static func createModule(listType: [WidgetTypeEntity]) -> EditServiceViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = EditServiceViewController.initFromNib()
        let interactor = EditServiceInteractor()
        let router = EditServiceRouter()
        let presenter = EditServicePresenter(interface: view,
                                             interactor: interactor,
                                             router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view.isAddNew = true
        view.listType = listType

        return view
    }
}
