//
//  HomeViewController.swift
//  CodeBase
//
//  Created DINH VAN TIEN on 2/12/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

let listTitle = ["Trang chủ",
                 "Lễ tân",
                 "Phiếu thu",
                 "Phiếu chi",
                 "Báo cáo thống kê",
                 "Giao ca",
                 "Cài đặt giá phòng",
                 "Quản lý tầng/ lầu",
                 "Dịch vụ",
                 "Cấu hình hệ thống",
                 "Thông tin khách sạn"]
let listImageTitle = [AppImage.receptionist,
                     AppImage.receipts,
                     AppImage.payment,
                     AppImage.statistic,
                     AppImage.shift,
                     AppImage.setting,
                     AppImage.manage,
                     AppImage.service,
                     AppImage.settingSystem,
                     AppImage.info]


class HomeViewController: HomeBaseViewController {

    @IBOutlet weak var cvHome: UICollectionView!
    @IBOutlet weak var lbService: UILabel!
    @IBOutlet weak var lbRoom: UILabel!
    @IBOutlet weak var lbTotal: UILabel!

    var presenter: HomePresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
        configureCollectionView()
//        presenter?.getReceiptReport(period: 1)
        if let user = UserDefaultHelper.shared.getUser(), let shiftID = user.ShiftId {
            presenter?.reportRevenue(shiftID: shiftID)
        }

    }

    override func setUpNavigation() {
        setTitleNavigation(title: "Trang chủ")
    }

    private func configureCollectionView() {
        cvHome.registerCollectionCell(HomeCVCell.self)
        cvHome.delegate = self
        cvHome.dataSource = self
        let screen = UIScreen.main.bounds
        let layout = UICollectionViewFlowLayout()
        layout.itemSize = CGSize(width: screen.width/2, height: screen.width/4)
        layout.minimumLineSpacing = 0
        layout.minimumInteritemSpacing = 0
        cvHome.collectionViewLayout = layout
    }

}

extension HomeViewController: HomeViewProtocol {
    func didReportRevenue(result: RevenueEntity?, error: APIError?) {
        if let result = result, let today = result.Today {
            lbService.text = "\(today.ServiceAmount*.formattedWithSeparator)"
            lbRoom.text = "\(today.RoomAmount*.formattedWithSeparator)"
            lbTotal.text = "\(today.Cashed*.formattedWithSeparator)"
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }

    func didGetReceiptReport(result: [ReceipReportEntity]?, error: APIError?) {
        if let result = result, result.count > 7 {
            lbService.text = "\(result[6].Amount*.formattedWithSeparator)"
            lbTotal.text = "\(result[6].Amount*.formattedWithSeparator)"
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }

}

extension HomeViewController: UICollectionViewDelegateFlowLayout, UICollectionViewDataSource {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return listTitle.count - 1
    }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueCollectionCell(HomeCVCell.self, indexPath: indexPath)
        cell.lbTitle.text = listTitle[indexPath.row + 1]
        cell.imgLogo.image = listImageTitle[indexPath.row]
        return cell
    }

    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if indexPath.row == 0 {
            let vc = TabbarReceptionistRouter.createModule()
            sideMenuController?.setContentViewController(to: vc)
        } else {
            self.showAlert(title: "Đang cập nhật", message: "Chức năng đang được cập nhật")
        }

    }
}
