//
//  HomeInteractor.swift
//  CodeBase
//
//  Created DINH VAN TIEN on 2/12/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class HomeInteractor: HomeInteractorInputProtocol {
    func reportRevenue(shiftID: Int) {
        service.reportRevenue(shiftID: shiftID, success: { (result) in
            self.presenter?.didReportRevenue(result: result, error: nil)
        }) { (error) in
            self.presenter?.didReportRevenue(result: nil, error: error)
        }
    }


    let service = Provider.shared.userAPIService

    func getReceiptReport(period: Int) {
        service.getReceiptReport(period: period, success: { (result) in
            self.presenter?.didGetReceiptReport(result: result, error: nil)
        }) { (error) in
            self.presenter?.didGetReceiptReport(result: nil, error: error)
        }
    }


    weak var presenter: HomeInteractorOutputProtocol?
}
