//
//  MoreRateSettingRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/24/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class MoreRateSettingRouter: MoreRateSettingWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(priceConfigure: ConfigPriceEntity?) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MoreRateSettingViewController(nibName: nil, bundle: nil)
        let interactor = MoreRateSettingInteractor()
        let router = MoreRateSettingRouter()
        let presenter = MoreRateSettingPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view.configurePrice = priceConfigure

        return view
    }
}
