//
//  MoreRateSettingInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/24/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class MoreRateSettingInteractor: MoreRateSettingInteractorInputProtocol {

    weak var presenter: MoreRateSettingInteractorOutputProtocol?
}
