//
//  MoreRateSettingViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/24/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

enum Surchanrge: Int, CaseIterable {
    case checkoutDayList
    case checkoutNightList
    case checkinDayList
    case checkinNightList
    case addtionCustomerList
}

class MoreRateSettingViewController: BaseViewController {
    
    @IBOutlet weak var tableView: UITableView!

	var presenter: MoreRateSettingPresenterProtocol?
    
    var configurePrice: ConfigPriceEntity?

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
    }
    
    override func setUpNavigation() {
        addBackWhiteToNavigation()
        setTitleNavigation(title: "Phụ thu")
    }
    
    private func configureTableView() {
        tableView.registerTableCell(MoreRateSettingCell.self)
        tableView.register(header: HeaderMoreRateSettingCell.self)
        tableView.delegate = self
        tableView.dataSource = self
        tableView.rowHeight = UITableView.automaticDimension
        tableView.sectionHeaderHeight = UITableView.automaticDimension
        tableView.estimatedSectionHeaderHeight = 40
        tableView.tableFooterView = UIView()
    }
}

extension MoreRateSettingViewController: MoreRateSettingViewProtocol {
	
}

extension MoreRateSettingViewController: UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return Surchanrge.allCases.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let configure = configurePrice else { return 0}
        switch section {
        case Surchanrge.checkoutDayList.rawValue:
            return configure.CheckoutDayList.count
        case Surchanrge.checkoutNightList.rawValue:
            return configure.CheckoutNightList.count
        case Surchanrge.checkinDayList.rawValue:
            return configure.CheckinDayList.count
        case Surchanrge.checkinNightList.rawValue:
            return configure.CheckinNightList.count
        case Surchanrge.addtionCustomerList.rawValue:
            return configure.AddtionCustomerList.count
        default:
            return 0
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(MoreRateSettingCell.self)
        cell.setData(configure: configurePrice, indexPath: indexPath)
        return cell
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let header = tableView.dequeue(header: HeaderMoreRateSettingCell.self)
        header.setShadawHeader()
        header.setData(section: section)
        return header
    }
    
}

extension MoreRateSettingViewController: UITableViewDelegate {
    
}
