//
//  AddSurchargeViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

enum SurchanrgeType: Int, CaseIterable {
    case checkoutDayList
    case checkoutNightList
    case checkinDayList
    case checkinNightList
    case priceByHour
    case addtionCustomerList
}

class AddSurchargeViewController: BaseViewController {
    
    @IBOutlet weak var tableView: UITableView!

	var presenter: AddSurchargePresenterProtocol?
    
    var configPrice = ConfigPriceEntity() {
        didSet {
            tableView.reloadData()
        }
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
    }
    
    override func setUpNavigation() {
        setTitleNavigation(title: "Thêm mới loại phòng")
        addBackWhiteToNavigation()
    }

    private func configureTableView() {
        tableView.registerTableCell(AddSurchargeCell.self)
        tableView.register(header: HeaderSurchargeCell.self)
        tableView.dataSource = self
        tableView.delegate = self
        tableView.rowHeight = UITableView.automaticDimension
        tableView.sectionHeaderHeight = UITableView.automaticDimension
        tableView.estimatedSectionHeaderHeight = 30
    }

    @IBAction func acceptButtonTapped() {
        self.navigationController?.dismiss()
    }
}

extension AddSurchargeViewController: AddSurchargeViewProtocol {
	
}

extension AddSurchargeViewController: UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return SurchanrgeType.allCases.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        switch section {
        case SurchanrgeType.checkinDayList.rawValue:
            return configPrice.CheckinDayList.count
        case SurchanrgeType.checkoutDayList.rawValue:
            return configPrice.CheckoutDayList.count
        case SurchanrgeType.checkinNightList.rawValue:
            return configPrice.CheckinNightList.count
        case SurchanrgeType.checkoutNightList.rawValue:
            return configPrice.CheckoutNightList.count
        case SurchanrgeType.priceByHour.rawValue:
            return configPrice.PriceByDayList.count
        case SurchanrgeType.addtionCustomerList.rawValue:
            return configPrice.AddtionCustomerList.count
        default:
            return 0
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(AddSurchargeCell.self)
        cell.setData(indexPath: indexPath)
        cell.removeSurchargeCallback = { [weak self] indexpath in
            guard let self = self else { return }
            self.removeSurcharge(indexpath: indexpath)
        }
        return cell
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let header = tableView.dequeue(header: HeaderSurchargeCell.self)
        header.setTitle(section: section)
        header.setShadawHeader()
        header.addCallback = { [weak self] section in
            guard let self = self else { return }
            self.addSurcharge(section: section)
        }
        return header
    }
    
    private func removeSurcharge(indexpath: IndexPath) {
        switch indexpath.section {
        case SurchanrgeType.checkinDayList.rawValue:
            self.configPrice.CheckinDayList.remove(at: indexpath.row)
        case SurchanrgeType.checkoutDayList.rawValue:
            self.configPrice.CheckoutDayList.remove(at: indexpath.row)
        case SurchanrgeType.checkinNightList.rawValue:
            self.configPrice.CheckinNightList.remove(at: indexpath.row)
        case SurchanrgeType.checkoutNightList.rawValue:
            self.configPrice.CheckoutNightList.remove(at: indexpath.row)
        case SurchanrgeType.priceByHour.rawValue:
            self.configPrice.PriceByDayList.remove(at: indexpath.row)
        case SurchanrgeType.addtionCustomerList.rawValue:
            self.configPrice.AddtionCustomerList.remove(at: indexpath.row)
        default:
            break
        }
        tableView.reloadData()
    }
    
    private func addSurcharge(section: Int) {
        switch section {
        case SurchanrgeType.checkinDayList.rawValue:
            self.configPrice.CheckinDayList.append(CheckoutEntity())
        case SurchanrgeType.checkoutDayList.rawValue:
            self.configPrice.CheckoutDayList.append(CheckoutEntity())
        case SurchanrgeType.checkinNightList.rawValue:
            self.configPrice.CheckinNightList.append(CheckoutEntity())
        case SurchanrgeType.checkoutNightList.rawValue:
            self.configPrice.CheckoutNightList.append(CheckoutEntity())
        case SurchanrgeType.priceByHour.rawValue:
            self.configPrice.PriceByDayList.append(CheckoutEntity())
        case SurchanrgeType.addtionCustomerList.rawValue:
            self.configPrice.AddtionCustomerList.append(CheckoutEntity())
        default:
            break
        }
        tableView.reloadData()
    }
    
}

extension AddSurchargeViewController: UITableViewDelegate {
    
}
