//
//  AddSurchargeRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddSurchargeRouter: AddSurchargeWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(param: RateSettingEntity) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AddSurchargeViewController(nibName: nil, bundle: nil)
        let interactor = AddSurchargeInteractor()
        let router = AddSurchargeRouter()
        let presenter = AddSurchargePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view.param = param

        return view
    }
}
