//
//  AddSurchargeProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol AddSurchargeWireframeProtocol: class {

}
//MARK: Presenter -
protocol AddSurchargePresenterProtocol: class {

    var interactor: AddSurchargeInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol AddSurchargeInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol AddSurchargeInteractorInputProtocol: class {

    var presenter: AddSurchargeInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol AddSurchargeViewProtocol: class {

    var presenter: AddSurchargePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
