//
//  AddSurchargePresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddSurchargePresenter: AddSurchargePresenterProtocol {

    weak private var view: AddSurchargeViewProtocol?
    var interactor: AddSurchargeInteractorInputProtocol?
    private let router: AddSurchargeWireframeProtocol

    init(interface: AddSurchargeViewProtocol, interactor: AddSurchargeInteractorInputProtocol?, router: AddSurchargeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension AddSurchargePresenter: AddSurchargeInteractorOutputProtocol {
	
}