//
//  AddSurchargePresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddSurchargePresenter: AddSurchargePresenterProtocol {
    func addOrUpdateConfigPrice(param: AddOrUpdateConfigPriceParam) {
        interactor?.addOrUpdateConfigPrice(param: param)
    }
    
    func addRoomClass(param: RateSettingEntity) {
        interactor?.addRoomClass(param: param)
    }
    

    weak private var view: AddSurchargeViewProtocol?
    var interactor: AddSurchargeInteractorInputProtocol?
    private let router: AddSurchargeWireframeProtocol

    init(interface: AddSurchargeViewProtocol, interactor: AddSurchargeInteractorInputProtocol?, router: AddSurchargeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension AddSurchargePresenter: AddSurchargeInteractorOutputProtocol {
    func didAddOrUpdateConfigPrice(result: [RateSettingEntity]?, error: APIError?) {
        view?.didAddOrUpdateConfigPrice(result: result, error: error)
    }
    
    func didAddRoomClass(result: [RateSettingEntity]?, error: APIError?) {
        view?.didAddRoomClass(result: result, error: error)
    }
}
