//
//  AddSurchargeInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddSurchargeInteractor: AddSurchargeInteractorInputProtocol {
    let service = Provider.shared.rateSettingAPIService
    
    func addRoomClass(param: RateSettingEntity) {
        service.addRoomClass(param: param) { (result) in
            self.presenter?.didAddRoomClass(result: result, error: nil)
        } failure: { (error) in
            self.presenter?.didAddRoomClass(result: nil, error: error)
        }

    }
    

    weak var presenter: AddSurchargeInteractorOutputProtocol?
}
