//
//  ListCustomerInteractor.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListCustomerInteractor: ListCustomerInteractorInputProtocol {

    let service = Provider.shared.receptionistAPIService

    func getListCustomerCheckIn() {
        service.getListCustomerCheckIn(success: { (result) in
            self.presenter?.didGetListCustomerCheckIn(result: result, error: nil)
        }) { (error) in
            self.presenter?.didGetListCustomerCheckIn(result: nil, error: error)
        }
    }


    weak var presenter: ListCustomerInteractorOutputProtocol?
}
