//
//  ListCustomerViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListCustomerViewController: HomeBaseViewController {

	var presenter: ListCustomerPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func setUpNavigation() {
        setTitleNavigation(title: "Khách đang ở")
    }


}

extension ListCustomerViewController: ListCustomerViewProtocol {
	
}
