//
//  ListCustomerPresenter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListCustomerPresenter: ListCustomerPresenterProtocol {
    func getListCustomerCheckIn() {
        interactor?.getListCustomerCheckIn()
    }


    weak private var view: ListCustomerViewProtocol?
    var interactor: ListCustomerInteractorInputProtocol?
    private let router: ListCustomerWireframeProtocol

    init(interface: ListCustomerViewProtocol, interactor: ListCustomerInteractorInputProtocol?, router: ListCustomerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension ListCustomerPresenter: ListCustomerInteractorOutputProtocol {
    func didGetListCustomerCheckIn(result: CustomerCheckInEntity?, error: APIError?) {
        view?.didGetListCustomerCheckIn(result: result, error: error)
    }

	
}
