//
//  LeftMenuPresenter.swift
//  CodeBase
//
//  Created DINH VAN TIEN on 2/12/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class LeftMenuPresenter: LeftMenuPresenterProtocol {

    weak private var view: LeftMenuViewProtocol?
    var interactor: LeftMenuInteractorInputProtocol?
    private let router: LeftMenuWireframeProtocol

    init(interface: LeftMenuViewProtocol, interactor: LeftMenuInteractorInputProtocol?, router: LeftMenuWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension LeftMenuPresenter: LeftMenuInteractorOutputProtocol {
	
}