//
//  LeftMenuRouter.swift
//  CodeBase
//
//  Created DINH VAN TIEN on 2/12/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class LeftMenuRouter: LeftMenuWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LeftMenuViewController(nibName: nil, bundle: nil)
        let interactor = LeftMenuInteractor()
        let router = LeftMenuRouter()
        let presenter = LeftMenuPresenter(interface: view,
                                          interactor: interactor,
                                          router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
