//
//  ListServiceRouter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 3/21/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListServiceRouter: ListServiceWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> ListServiceViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ListServiceViewController.initFromNib()
        let interactor = ListServiceInteractor()
        let router = ListServiceRouter()
        let presenter = ListServicePresenter(interface: view,
                                             interactor: interactor,
                                             router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
