//
//  SignUpInteractor.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 4/30/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class SignUpInteractor: SignUpInteractorInputProtocol {

    let service = Provider.shared.userAPIService

    func register(param: RegisterParam) {
        service.register(param: param, success: { (result) in
            self.presenter?.didRegister(result: result, error: nil)
        }) { (error) in
            self.presenter?.didRegister(result: nil, error: error)
        }
    }

    func completedRegiser(param: CompleteRegisterParam) {
        service.completedRegiser(param: param, success: { (result) in
            self.presenter?.didCompletedRegiser(result: result, error: nil)
        }) { (error) in
            self.presenter?.didCompletedRegiser(result: nil, error: error)
        }
    }


    weak var presenter: SignUpInteractorOutputProtocol?
}
