//
//  PaymentViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/7/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class PaymentViewController: HomeBaseViewController {
    
    @IBOutlet weak var tbPayment: UITableView!

	var presenter: PaymentPresenterProtocol?
    
    var listPayment: [PaymentEntity] = [] {
        didSet {
            self.tbPayment.reloadData()
        }
    }
    
    var refreshControl = UIRefreshControl()

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
        
        refreshControl.attributedTitle = NSAttributedString(string: "Pull to refresh")
        refreshControl.addTarget(self, action: #selector(refreshData), for: .valueChanged)
        tbPayment.addSubview(refreshControl) // not required when using UITableViewController
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        refreshData()
    }

    deinit {
        NotificationCenter.default.removeObserver(self)
    }
    
    @objc private func refreshData() {
        let param = GetInvoiceParam.setDefaultPaymentParam()
        presenter?.getInvoiceByPayment(param: param)
    }
    
    override func setUpNavigation() {
        setTitleNavigation(title: "Phiếu chi")
    }

    private func configureTableView() {
        tbPayment.registerTableCell(PaymentCell.self)
        tbPayment.delegate = self
        tbPayment.dataSource = self
        tbPayment.rowHeight = UITableView.automaticDimension
        tbPayment.contentInset.bottom = 50
    }

}

extension PaymentViewController: PaymentViewProtocol {
    func didGetInvoiceByPayment(result: PaymentEntityResponse?, error: APIError?) {
        if let result = result {
            self.listPayment = result.payment
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }
    
	
}

extension PaymentViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listPayment.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(PaymentCell.self)
        cell.invoice = listPayment[indexPath.row]
        return cell
    }
}
