//
//  PaymentProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/7/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol PaymentWireframeProtocol: class {

}
//MARK: Presenter -
protocol PaymentPresenterProtocol: class {

    var interactor: PaymentInteractorInputProtocol? { get set }
    
    func getInvoiceByPayment(param: GetInvoiceParam)
}

//MARK: Interactor -
protocol PaymentInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetInvoiceByPayment(result: PaymentEntityResponse?, error: APIError?)
}

protocol PaymentInteractorInputProtocol: class {

    var presenter: PaymentInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getInvoiceByPayment(param: GetInvoiceParam)
}

//MARK: View -
protocol PaymentViewProtocol: class {

    var presenter: PaymentPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetInvoiceByPayment(result: PaymentEntityResponse?, error: APIError?)
}
