//
//  PaymentInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/7/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class PaymentInteractor: PaymentInteractorInputProtocol {
    
    let service = Provider.shared.paymentAPIService
    
    func getInvoiceByPayment(param: GetInvoiceParam) {
        service.getInvoiceByPayment(param: param, success: { (result) in
            self.presenter?.didGetInvoiceByPayment(result: result, error: nil)
        }) { (error) in
            self.presenter?.didGetInvoiceByPayment(result: nil, error: error)
        }
    }
    

    weak var presenter: PaymentInteractorOutputProtocol?
}
