//
//  ListCustomerProtocols.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol ListCustomerWireframeProtocol: class {

}
//MARK: Presenter -
protocol ListCustomerPresenterProtocol: class {

    var interactor: ListCustomerInteractorInputProtocol? { get set }
    func getListCustomerCheckIn()
}

//MARK: Interactor -
protocol ListCustomerInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetListCustomerCheckIn(result: CustomerCheckInEntity?, error: APIError?)
}

protocol ListCustomerInteractorInputProtocol: class {

    var presenter: ListCustomerInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getListCustomerCheckIn()
}

//MARK: View -
protocol ListCustomerViewProtocol: class {

    var presenter: ListCustomerPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetListCustomerCheckIn(result: CustomerCheckInEntity?, error: APIError?)
}
