//
//  CheckInViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CheckInViewController: BaseViewController {

    @IBOutlet weak var tfCustomerName       : AppTextFieldLogo!
    @IBOutlet weak var tfIndentifierNumber  : AppTextFieldLogo!
    @IBOutlet weak var tfIndentifierDate    : TextFieldCalendar!
    @IBOutlet weak var tfAdress             : AppTextFieldLogo!
    @IBOutlet weak var tfCheckInTime        : TextFieldCalendar!
    @IBOutlet weak var vTimeType            : AppDropdown!
    @IBOutlet weak var vConfigurePrice      : AppDropdown!
    @IBOutlet weak var vService             : AppDropdownBorder!
    @IBOutlet weak var vTotalService        : AppDropdownBorder!
    @IBOutlet weak var tvNote               : AppTextViewLogo!

	var presenter: CheckInPresenterProtocol?

    var listPrice: [ConfigPriceEntity] = [] {
        didSet {
            self.vConfigurePrice.dataSource = self.listPrice.map({$0.Name&})
        }
    }

    var room: RoomEntity?

	override func viewDidLoad() {
        super.viewDidLoad()
        getData()
    }

    private func getData() {
        guard let room = room, let roomId = room.Id else { return }
        presenter?.getConfigPrice(roomId: roomId)
    }

    override func setUpNavigation() {
        setTitleNavigation(title: "Nhận phòng")
        addBackWhiteToNavigation()
        addButtonTextToNavigation(title: "Nhận", style: .right, action: #selector(btnAcceptTapped))
    }

    override func setUpViews() {
        tfCustomerName.setTitleAndLogo(AppImage.imgPayment, title: "Khách hàng")
        tfIndentifierNumber.setTitleAndLogo(AppImage.imgPayment, title: "CMT")
        tfAdress.setTitleAndLogo(AppImage.imgPayment, title: "Địa chỉ")

        vTimeType.setTitleAndLogo(AppImage.imgPayment, title: "Tính theo")
        vConfigurePrice.setTitleAndLogo(AppImage.imgPayment, title: "Cấu hình giá")
        vService.setTitleAndLogo(AppImage.imgPayment, title: "Dịch vụ")


        tfIndentifierDate.setTitleAndLogo(AppImage.imgPayment, title: "Ngày cấp")

        tfIndentifierDate.setTitleAndLogo(AppImage.imgPayment, title: "Thời gian")

        tvNote.setTitleAndLogo(AppImage.imgPayment, title: "Ghi chú")
        vTotalService.dataSource = ["1", "2", "3", "4", "5"]
        vService.dataSource = ["Dịch vụ"]

    }

    @objc func btnAcceptTapped() {

    }

}

extension CheckInViewController: CheckInViewProtocol {
    func didGetConfigPrice(result: [ConfigPriceEntity]?, error: APIError?) {
        if let result = result {
            self.listPrice = result
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }

	
}
