//
//  CheckInPresenter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CheckInPresenter: CheckInPresenterProtocol {

    weak private var view: CheckInViewProtocol?
    var interactor: CheckInInteractorInputProtocol?
    private let router: CheckInWireframeProtocol

    init(interface: CheckInViewProtocol, interactor: CheckInInteractorInputProtocol?, router: CheckInWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension CheckInPresenter: CheckInInteractorOutputProtocol {
	
}