//
//  CheckInRouter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CheckInRouter: CheckInWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(room: RoomEntity?) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CheckInViewController(nibName: nil, bundle: nil)
        let interactor = CheckInInteractor()
        let router = CheckInRouter()
        let presenter = CheckInPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view.room = room

        return view
    }
}
