//
//  CheckInInteractor.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CheckInInteractor: CheckInInteractorInputProtocol {

    weak var presenter: CheckInInteractorOutputProtocol?
}
