//
//  CheckInViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CheckInViewController: BaseViewController {

	var presenter: CheckInPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func setUpNavigation() {
        setTitleNavigation(title: "Nhận phòng")
        addBackWhiteToNavigation()
        addButtonTextToNavigation(title: "Nhận", style: .right, action: #selector(btnAcceptTapped))
    }

    @objc func btnAcceptTapped() {

    }

}

extension CheckInViewController: CheckInViewProtocol {
	
}
