//
//  DetailRateSettingProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/11/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol DetailRateSettingWireframeProtocol: class {

}
//MARK: Presenter -
protocol DetailRateSettingPresenterProtocol: class {

    var interactor: DetailRateSettingInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol DetailRateSettingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol DetailRateSettingInteractorInputProtocol: class {

    var presenter: DetailRateSettingInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol DetailRateSettingViewProtocol: class {

    var presenter: DetailRateSettingPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
