//
//  DetailRateSettingInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/11/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class DetailRateSettingInteractor: DetailRateSettingInteractorInputProtocol {

    weak var presenter: DetailRateSettingInteractorOutputProtocol?
}
