//
//  DetailRateSettingRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/11/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class DetailRateSettingRouter: DetailRateSettingWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(priceList: [CheckoutEntity]) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DetailRateSettingViewController(nibName: nil, bundle: nil)
        let interactor = DetailRateSettingInteractor()
        let router = DetailRateSettingRouter()
        let presenter = DetailRateSettingPresenter(interface: view,
                                                   interactor: interactor,
                                                   router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view.priceByDayList = priceList

        return view
    }
}
