//
//  DetailRateSettingViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/11/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class DetailRateSettingViewController: BaseViewController {
    
    @IBOutlet weak var detailTable: UITableView!

	var presenter: DetailRateSettingPresenterProtocol?
    
    var priceByDayList: [CheckoutEntity] = []

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
    }
    
    override func setUpNavigation() {
        addBackWhiteToNavigation()
        setTitleNavigation(title: "Giá phòng theo giờ")
    }
    
    private func configureTableView() {
        detailTable.registerTableCell(HourRateSettingCell.self)
        detailTable.delegate = self
        detailTable.dataSource = self
        detailTable.rowHeight = UITableView.automaticDimension
        detailTable.tableFooterView = UIView()
    }

}

extension DetailRateSettingViewController: DetailRateSettingViewProtocol {
	
}

extension DetailRateSettingViewController: UITableViewDelegate {
    
}

extension DetailRateSettingViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return priceByDayList.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(HourRateSettingCell.self)
        cell.setData(detail: priceByDayList[indexPath.row], row: indexPath.row)
        return cell
    }
    
    func tableView(_ tableView: UITableView, titleForFooterInSection section: Int) -> String? {
        return "Vượt quá thời gian trên tính 1 ngày"
    }
    
    func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        return 40
    }
}
