//
//  CheckOutViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 3/21/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CheckOutViewController: BaseViewController {

    @IBOutlet weak var tbCheckOut: UITableView!

	var presenter: CheckOutPresenterProtocol?

    var orderInfo: OrderInfoEntity? {
        didSet {
            tbCheckOut.reloadData()
        }
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.getOrderForCheckOut(orderId: 12197, mode: 1)
    }

    override func setUpNavigation() {
        addBackWhiteToNavigation()
    }

}

extension CheckOutViewController: CheckOutViewProtocol {
    func didGetOrderForCheckOut(result: OrderInfoEntity?, error: APIError?) {
        if let result = result {
            self.orderInfo = result
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }

	
}
