//
//  CheckOutInteractor.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 3/21/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CheckOutInteractor: CheckOutInteractorInputProtocol {
    let service = Provider.shared.receptionistAPIService

    func getOrderForCheckOut(orderId: Int, mode: Int) {
        service.getOrderForCheckOut(orderId: orderId, mode: mode, success: { (result) in
            self.presenter?.didGetOrderForCheckOut(result: result, error: nil)
        }) { (error) in
            self.presenter?.didGetOrderForCheckOut(result: nil, error: error)
        }
    }


    weak var presenter: CheckOutInteractorOutputProtocol?
}
