//
//  RateSettingListPresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 9/20/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class RateSettingListPresenter: RateSettingListPresenterProtocol {
    func getRoomClass() {
        interactor?.getRoomClass()
    }
    

    weak private var view: RateSettingListViewProtocol?
    var interactor: RateSettingListInteractorInputProtocol?
    private let router: RateSettingListWireframeProtocol

    init(interface: RateSettingListViewProtocol, interactor: RateSettingListInteractorInputProtocol?, router: RateSettingListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension RateSettingListPresenter: RateSettingListInteractorOutputProtocol {
    func didGetRoomClass(result: [RateSettingEntity]?, error: APIError?) {
        view?.didGetRoomClass(result: result, error: error)
    }
    
	
}
