//
//  RateSettingListViewController.swift
//  Bizkasa
//
//  Created Tien Dinh on 9/20/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class RateSettingListViewController: HomeBaseViewController {
    
    @IBOutlet weak var tbRateSetting: UITableView!

	var presenter: RateSettingListPresenterProtocol?
    
    var listRateSetting: [RateSettingEntity] = [] {
        didSet {
            tbRateSetting.reloadData()
        }
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
        presenter?.getRoomClass()
    }
    
    override func setUpNavigation() {
        setTitleNavigation(title: "Cài đặt giá phòng")
    }

    private func configureTableView() {
        tbRateSetting.registerTableCell(RateSettingCell.self)
        tbRateSetting.register(header: HeaderRateSettingCell.self)
        tbRateSetting.delegate = self
        tbRateSetting.dataSource = self
        tbRateSetting.rowHeight = UITableView.automaticDimension
    }
}

extension RateSettingListViewController: RateSettingListViewProtocol {
    func didGetRoomClass(result: [RateSettingEntity]?, error: APIError?) {
        if let result = result {
            self.listRateSetting = result
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }
}

extension RateSettingListViewController: UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return listRateSetting.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listRateSetting[section].ConfigPrices.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(RateSettingCell.self)
        cell.setData(detail: listRateSetting[indexPath.section].ConfigPrices[indexPath.row])
        return cell
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let header = tableView.dequeue(header: HeaderRateSettingCell.self)
        header.setData(detail: listRateSetting[section])
        return header
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 40
    }
}

extension RateSettingListViewController: UITableViewDelegate {
    
}
