//
//  RateSettingListRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 9/20/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class RateSettingListRouter: RateSettingListWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RateSettingListViewController(nibName: nil, bundle: nil)
        let interactor = RateSettingListInteractor()
        let router = RateSettingListRouter()
        let presenter = RateSettingListPresenter(interface: view,
                                                 interactor: interactor,
                                                 router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
