//
//  RoomManagementRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/19/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class RoomManagementRouter: RoomManagementWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RoomManagementViewController(nibName: nil, bundle: nil)
        let interactor = RoomManagementInteractor()
        let router = RoomManagementRouter()
        let presenter = RoomManagementPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
