//
//  RoomManagementProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/19/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol RoomManagementWireframeProtocol: class {

}
//MARK: Presenter -
protocol RoomManagementPresenterProtocol: class {

    var interactor: RoomManagementInteractorInputProtocol? { get set }
    
    func getFloorWithRoom(token: String)
}

//MARK: Interactor -
protocol RoomManagementInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetFloorWithRoom(result: [FloorEntity]?, error: APIError?)
}

protocol RoomManagementInteractorInputProtocol: class {

    var presenter: RoomManagementInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getFloorWithRoom(token: String)
}

//MARK: View -
protocol RoomManagementViewProtocol: class {

    var presenter: RoomManagementPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetFloorWithRoom(result: [FloorEntity]?, error: APIError?)
}
