//
//  RoomManagementPresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/19/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class RoomManagementPresenter: RoomManagementPresenterProtocol {
    func deleteFloor(id: Int) {
        interactor?.deleteFloor(id: id)
    }
    
    func insertOrUpdateFloor(param: InsertOrUpdateFloorParam) {
        interactor?.insertOrUpdateFloor(param: param)
    }
    
    func editRoom(param: EditRoomParam) {
        interactor?.editRoom(param: param)
    }
    
    func deleteRoom(id: Int) {
        interactor?.deleteRoom(id: id)
    }
    
    func getFloorWithRoom(token: String) {
        interactor?.getFloorWithRoom(token: token)
    }
    

    weak private var view: RoomManagementViewProtocol?
    var interactor: RoomManagementInteractorInputProtocol?
    private let router: RoomManagementWireframeProtocol

    init(interface: RoomManagementViewProtocol, interactor: RoomManagementInteractorInputProtocol?, router: RoomManagementWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension RoomManagementPresenter: RoomManagementInteractorOutputProtocol {
    func didDeleteFloor(result: BaseResponse?, error: APIError?) {
        view?.didDeleteFloor(result: result, error: error)
    }
    
    func didInsertOrUpdateFloor(result: BaseResponse?, error: APIError?) {
        view?.didInsertOrUpdateFloor(result: result, error: error)
    }
    
    func didEditRoom(result: BaseResponse?, error: APIError?) {
        view?.didEditRoom(result: result, error: error)
    }
    
    func didDeleteRoom(result: BaseResponse?, error: APIError?) {
        view?.didDeleteRoom(result: result, error: error)
    }
    
    func didGetFloorWithRoom(result: [FloorEntity]?, error: APIError?) {
        view?.didGetFloorWithRoom(result: result, error: error)
    }
    
	
}
