//
//  RoomManagementInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/19/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class RoomManagementInteractor: RoomManagementInteractorInputProtocol {
    
    let service = Provider.shared.roomManagementAPIService
    func getFloorWithRoom(token: String) {
        service.getFloorWithRoom(token: token, success: { (result) in
            self.presenter?.didGetFloorWithRoom(result: result, error: nil)
        }) { (error) in
            self.presenter?.didGetFloorWithRoom(result: nil, error: error)
        }
    }
    

    weak var presenter: RoomManagementInteractorOutputProtocol?
}
