//
//  RoomManagementPresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 7/19/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class RoomManagementPresenter: RoomManagementPresenterProtocol {
    func getFloorWithRoom(token: String) {
        interactor?.getFloorWithRoom(token: token)
    }
    

    weak private var view: RoomManagementViewProtocol?
    var interactor: RoomManagementInteractorInputProtocol?
    private let router: RoomManagementWireframeProtocol

    init(interface: RoomManagementViewProtocol, interactor: RoomManagementInteractorInputProtocol?, router: RoomManagementWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension RoomManagementPresenter: RoomManagementInteractorOutputProtocol {
    func didGetFloorWithRoom(result: [FloorEntity]?, error: APIError?) {
        view?.didGetFloorWithRoom(result: result, error: error)
    }
    
	
}
