//
//  CreateNewReceiptProtocols.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol CreateNewReceiptWireframeProtocol: class {

}
//MARK: Presenter -
protocol CreateNewReceiptPresenterProtocol: class {

    var interactor: CreateNewReceiptInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol CreateNewReceiptInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol CreateNewReceiptInteractorInputProtocol: class {

    var presenter: CreateNewReceiptInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol CreateNewReceiptViewProtocol: class {

    var presenter: CreateNewReceiptPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
