//
//  CreateNewReceiptViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CreateNewReceiptViewController: BaseViewController {

    @IBOutlet weak var vCustomerName: AppTextFieldLogo!
    @IBOutlet weak var vNote: AppTextFieldLogo!

    @IBOutlet weak var vService: ServiceView!

    @IBOutlet weak var lbEmployeeName: UILabel!
    @IBOutlet weak var lbCurrentTime: UILabel!

    @IBOutlet weak var tbListWidget: UITableView!
    @IBOutlet weak var lbTotalPrice: UILabel!
    @IBOutlet weak var vTotalPrice: UIView!

    var listWidget: [(WidgetEntity, Int)] = [] {
        didSet {
            let totalPrice = self.listWidget.reduce(Float(0)) { result, item in
                return result + (item.0.Price ?? 0) * Float(item.1)
            }
            vTotalPrice.isHidden = totalPrice == Float(0)
            lbTotalPrice.text = "\(totalPrice) VNĐ"
            tbListWidget.reloadData()
        }
    }

	var presenter: CreateNewReceiptPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
    }

    override func setUpNavigation() {
        addBackWhiteToNavigation()
        addButtonTextToNavigation(title: "Đồng ý", style: .right, action: #selector(btnAcceptTapped))
    }

    override func setUpViews() {
        vCustomerName.setTitleAndLogo(AppImage.imgUser, title: "Tên khách hàng")
        vCustomerName.setPlaceHolder(title: "Nhập tên khách hàng")
        vNote.setTitleAndLogo(AppImage.imgReceipts, title: "Ghi chú")
        vNote.setPlaceHolder(title: "Nhập ghi chú")
        vCustomerName.setHeightTitle(value: 20)
        vNote.setHeightTitle(value: 20)

        guard let user = UserDefaultHelper.shared.getUser() else { return }
        lbEmployeeName.text = "Nhân viên: \(user.Email&)"
        lbCurrentTime.text = "Thời gian: \(Date().toDateFormatCurrentTime(DateFormat.SIMPLE_DATE))"

        vService.addNewCallBack = {[weak self] (widget, total) in
            guard let self = self else { return }
            self.listWidget.append((widget, total))
        }
    }

    private func configureTableView() {
        tbListWidget.registerTableCell(WidgetCell.self)
        tbListWidget.dataSource = self
        tbListWidget.delegate = self
        tbListWidget.rowHeight = UITableView.automaticDimension
    }

    @objc func btnAcceptTapped() {

    }
}

extension CreateNewReceiptViewController: CreateNewReceiptViewProtocol {
	
}

extension CreateNewReceiptViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if listWidget.count == 0 {
            tableView.setEmptyView(title: "Chưa có dịch vụ")
        } else {
            tableView.restore()
        }
        return listWidget.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(WidgetCell.self)
        cell.setData(widget: listWidget[indexPath.row].0, total: listWidget[indexPath.row].1, indexPath: indexPath)
        cell.deleteCallback = { indexPath in
            self.listWidget.remove(at: indexPath.row)
        }
        return cell
    }
}

