//
//  FlashInteractor.swift
//  CodeBase
//
//  Created DINH VAN TIEN on 2/12/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class FlashInteractor: FlashInteractorInputProtocol {

    weak var presenter: FlashInteractorOutputProtocol?
}
