//
//  FlashViewController.swift
//  CodeBase
//
//  Created DINH VAN TIEN on 2/12/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class FlashViewController: UIViewController {

	var presenter: FlashPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
                if UtilsHelper.isIpad() {
                    SideMenuController.preferences.basic.menuWidth = 400
                } else {
                    SideMenuController.preferences.basic.menuWidth = 300
                }
                CATransaction.begin()
                CATransaction.setCompletionBlock({
                    let home = HomeRouter.createModule().convertNavi()
                    let menu = LeftMenuRouter.createModule()
                    let vc = SideMenuController(contentViewController: home, menuViewController: menu)
                    self.view.window?.rootViewController = vc
                })
                CATransaction.commit()
    }

}

extension FlashViewController: FlashViewProtocol {
	
}
