//
//  ListRoomViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/23/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListRoomViewController: HomeBaseViewController {

    @IBOutlet weak var cvListRoom: UICollectionView!

	var presenter: ListRoomPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        configureCollectionView()
    }

    private func configureCollectionView() {
        cvListRoom.registerCollectionCell(ListRoomCVCell.self)
        cvListRoom.delegate = self
        cvListRoom.dataSource = self
        let screen = UIScreen.main.bounds
        let layout = UICollectionViewFlowLayout()
        layout.itemSize = CGSize(width: screen.width/2, height: 60)
        layout.minimumLineSpacing = 0
        layout.minimumInteritemSpacing = 0
        cvListRoom.collectionViewLayout = layout
    }

}

extension ListRoomViewController: ListRoomViewProtocol {
	
}

extension ListRoomViewController: UICollectionViewDelegateFlowLayout, UICollectionViewDataSource {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 10
    }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueCollectionCell(ListRoomCVCell.self, indexPath: indexPath)
        return cell
    }


}
