//
//  ListRoomInteractor.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/23/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListRoomInteractor: ListRoomInteractorInputProtocol {

    let service = Provider.shared.receptionistAPIService

    func getRoomsByClass() {
        service.getRoomsByClass(success: { (result) in
            self.presenter?.didGetRoomsByClass(result: result, error: nil)
        }) { (error) in
            self.presenter?.didGetRoomsByClass(result: nil, error: error)
        }
    }


    weak var presenter: ListRoomInteractorOutputProtocol?
}
