//
//  ListRoomInteractor.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/23/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListRoomInteractor: ListRoomInteractorInputProtocol {

    weak var presenter: ListRoomInteractorOutputProtocol?
}
