//
//  ListRoomPresenter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/23/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListRoomPresenter: ListRoomPresenterProtocol {

    weak private var view: ListRoomViewProtocol?
    var interactor: ListRoomInteractorInputProtocol?
    private let router: ListRoomWireframeProtocol

    init(interface: ListRoomViewProtocol, interactor: ListRoomInteractorInputProtocol?, router: ListRoomWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension ListRoomPresenter: ListRoomInteractorOutputProtocol {
	
}