//
//  AddRateSettingPresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddRateSettingPresenter: AddRateSettingPresenterProtocol {

    weak private var view: AddRateSettingViewProtocol?
    var interactor: AddRateSettingInteractorInputProtocol?
    private let router: AddRateSettingWireframeProtocol

    init(interface: AddRateSettingViewProtocol,
         interactor: AddRateSettingInteractorInputProtocol?,
         router: AddRateSettingWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension AddRateSettingPresenter: AddRateSettingInteractorOutputProtocol {
	
}
