//
//  AddRateSettingInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 10/25/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddRateSettingInteractor: AddRateSettingInteractorInputProtocol {

    weak var presenter: AddRateSettingInteractorOutputProtocol?
}
