//
//  AddGeneralConfigurePresenter.swift
//  Bizkasa
//
//  Created Tien Dinh on 11/1/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddGeneralConfigurePresenter: AddGeneralConfigurePresenterProtocol {

    weak private var view: AddGeneralConfigureViewProtocol?
    var interactor: AddGeneralConfigureInteractorInputProtocol?
    private let router: AddGeneralConfigureWireframeProtocol

    init(interface: AddGeneralConfigureViewProtocol,
         interactor: AddGeneralConfigureInteractorInputProtocol?,
         router: AddGeneralConfigureWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension AddGeneralConfigurePresenter: AddGeneralConfigureInteractorOutputProtocol {
	
}
