//
//  AddGeneralConfigureProtocols.swift
//  Bizkasa
//
//  Created Tien Dinh on 11/1/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol AddGeneralConfigureWireframeProtocol: class {

}
//MARK: Presenter -
protocol AddGeneralConfigurePresenterProtocol: class {

    var interactor: AddGeneralConfigureInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol AddGeneralConfigureInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol AddGeneralConfigureInteractorInputProtocol: class {

    var presenter: AddGeneralConfigureInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol AddGeneralConfigureViewProtocol: class {

    var presenter: AddGeneralConfigurePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
