//
//  AddGeneralConfigureRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 11/1/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddGeneralConfigureRouter: AddGeneralConfigureWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AddGeneralConfigureViewController(nibName: nil, bundle: nil)
        let interactor = AddGeneralConfigureInteractor()
        let router = AddGeneralConfigureRouter()
        let presenter = AddGeneralConfigurePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
