//
//  AddGeneralConfigureRouter.swift
//  Bizkasa
//
//  Created Tien Dinh on 11/1/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddGeneralConfigureRouter: AddGeneralConfigureWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(rateSetting: RateSettingEntity, type: ConfigPriceType, configEdit: PriceEntity?) -> AddGeneralConfigureViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AddGeneralConfigureViewController.initFromNib()
        let interactor = AddGeneralConfigureInteractor()
        let router = AddGeneralConfigureRouter()
        let presenter = AddGeneralConfigurePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.type = type
        if type == .EditConfigPrice {
            view.addOrUpdateConfigParam.ConfigPrice = configEdit
        }
        view.addOrUpdateConfigParam.roomClassId = rateSetting.RoomClass?.Id

        return view
    }
}
