//
//  AddGeneralConfigureInteractor.swift
//  Bizkasa
//
//  Created Tien Dinh on 11/1/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class AddGeneralConfigureInteractor: AddGeneralConfigureInteractorInputProtocol {

    weak var presenter: AddGeneralConfigureInteractorOutputProtocol?
}
