//
//  TabbarReceptionistViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit
import BATabBarController

class TabbarReceptionistViewController: UITabBarController {

	var presenter: TabbarReceptionistPresenterProtocol?
    
	override func viewDidLoad() {
        super.viewDidLoad()
        self.delegate = self
        let listRoom = ListRoomRouter.createModule().convertNavi()
        let iconRoom = UITabBarItem(title: "Phòng", image: AppImage.imgRoom, selectedImage: AppImage.imgRoom)
        listRoom.tabBarItem = iconRoom

        let listCustomer = ListCustomerRouter.createModule().convertNavi()
               let iconCustomer = UITabBarItem(title: "Khách", image: AppImage.imgUser, selectedImage: AppImage.imgUser)
               listCustomer.tabBarItem = iconCustomer

        let listReceipt = ListReceiptRouter.createModule().convertNavi()
               let iconReceipt = UITabBarItem(title: "Phiếu thu", image: AppImage.imgPayment, selectedImage: AppImage.imgPayment)
               listReceipt.tabBarItem = iconReceipt
        let controllers = [listRoom, listReceipt, listCustomer]  //array of the root view controllers displayed by the tab bar interface
        self.viewControllers = controllers
        
        for tabBarItem in tabBar.items! {
            
            tabBarItem.imageInsets = UIEdgeInsets(top: 5, left: 0, bottom: 5, right: 0)
        }
    }
}

extension TabbarReceptionistViewController: BATabBarControllerDelegate, UITabBarControllerDelegate {
    func tabBarController(_ tabBarController: BATabBarController, didSelect: UIViewController) {

    }
    
    override func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        guard let barButtonView = item.value(forKey: "view") as? UIView else { return }
        barButtonView.setAnimationTouch()
    }
}

extension TabbarReceptionistViewController: TabbarReceptionistViewProtocol {
	
}

extension TabbarReceptionistViewController {
    
}
