//
//  TabbarReceptionistViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit
import BATabBarController

extension UIImage {
    func customTint(_ tintColor: UIColor = AppColor.normalOrange) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(self.size, false, self.scale)
        let context: CGContext = UIGraphicsGetCurrentContext()!
        context.translateBy(x: 0, y: self.size.height)
        context.scaleBy(x: 1.0, y: -1.0)
        context.setBlendMode(CGBlendMode.normal)
        let rect: CGRect = CGRect(x: 0, y: 0, width: self.size.width, height: self.size.height)

        context.clip(to: rect, mask: self.cgImage!)

        tintColor.setFill()
        context.fill(rect)

        var newImage: UIImage = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        newImage = newImage.withRenderingMode(UIImage.RenderingMode.alwaysOriginal)
        return newImage
    }
}

class TabbarReceptionistViewController: UITabBarController {
    
    var presenter: TabbarReceptionistPresenterProtocol?
    
    let selectColor = AppColor.main
    let unselectColor = AppColor.normalGray
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.delegate = self
        let listRoom = ListRoomRouter.createModule().convertNavi()
        let iconRoom = UITabBarItem(title: "Phòng",
                                    image: AppImage.imgRoom.customTint(unselectColor),
                                    selectedImage: AppImage.imgRoom.customTint(selectColor))
        listRoom.tabBarItem = iconRoom
        
        let listCustomer = ListCustomerRouter.createModule().convertNavi()
        let iconCustomer = UITabBarItem(
            title: "Khách",
            image: AppImage.imgUser.customTint(unselectColor),
            selectedImage: AppImage.imgUser.customTint(selectColor))
        listCustomer.tabBarItem = iconCustomer
        
        let listReceipt = ListReceiptRouter.createModule().convertNavi()
        let iconReceipt = UITabBarItem(
            title: "Phiếu thu",
            image: AppImage.imgPayment.customTint(unselectColor),
            selectedImage: AppImage.imgPayment.customTint(selectColor))
        listReceipt.tabBarItem = iconReceipt
        let controllers = [listRoom, listReceipt, listCustomer]
        self.viewControllers = controllers
        
        for tabBarItem in tabBar.items! {
            tabBarItem.imageInsets = UIEdgeInsets(top: 3, left: 0, bottom: 3, right: 0)
        }
        
        
        UITabBarItem.appearance().setTitleTextAttributes([NSAttributedString.Key.foregroundColor: unselectColor], for: .normal)
        UITabBarItem.appearance().setTitleTextAttributes([NSAttributedString.Key.foregroundColor: selectColor], for: .selected)
        
        tabBar.isTranslucent = false
        tabBar.layer.shadowOffset = CGSize(width: 0, height: 0)
        tabBar.layer.shadowRadius = 3
        tabBar.layer.shadowColor = UIColor.black.cgColor
        tabBar.layer.shadowOpacity = 0.3
        
        tabBar.shadowImage = UIImage()
        tabBar.backgroundImage = UIImage()
        
    }
}

extension TabbarReceptionistViewController: BATabBarControllerDelegate, UITabBarControllerDelegate {
    func tabBarController(_ tabBarController: BATabBarController, didSelect: UIViewController) {
        
    }
    
    override func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        guard let barButtonView = item.value(forKey: "view") as? UIView else { return }
        barButtonView.setAnimationTouch()
    }
}

extension TabbarReceptionistViewController: TabbarReceptionistViewProtocol {
    
}

extension TabbarReceptionistViewController {
    
}
