//
//  TabbarReceptionistRouter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class TabbarReceptionistRouter: TabbarReceptionistWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = TabbarReceptionistViewController(nibName: nil, bundle: nil)
        let interactor = TabbarReceptionistInteractor()
        let router = TabbarReceptionistRouter()
        let presenter = TabbarReceptionistPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
