//
//  TabbarReceptionistViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class TabbarReceptionistViewController: UITabBarController {

	var presenter: TabbarReceptionistPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()

        let listRoom = ListRoomRouter.createModule().convertNavi()
        let iconRoom = UITabBarItem(title: "Phòng", image: AppImage.imgRoom, selectedImage: AppImage.imgRoom)
        listRoom.tabBarItem = iconRoom

        let listCustomer = ListCustomerRouter.createModule().convertNavi()
               let iconCustomer = UITabBarItem(title: "Khách", image: AppImage.imgUser, selectedImage: AppImage.imgUser)
               listCustomer.tabBarItem = iconCustomer

        let listReceipt = ListReceiptRouter.createModule().convertNavi()
               let iconReceipt = UITabBarItem(title: "Phiếu thu", image: AppImage.imgPayment, selectedImage: AppImage.imgPayment)
               listReceipt.tabBarItem = iconReceipt
        let controllers = [listRoom, listCustomer, listReceipt]  //array of the root view controllers displayed by the tab bar interface
        self.viewControllers = controllers
    }

}

extension TabbarReceptionistViewController: TabbarReceptionistViewProtocol {
	
}
