//
//  TabbarReceptionistProtocols.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol TabbarReceptionistWireframeProtocol: class {

}
//MARK: Presenter -
protocol TabbarReceptionistPresenterProtocol: class {

    var interactor: TabbarReceptionistInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol TabbarReceptionistInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol TabbarReceptionistInteractorInputProtocol: class {

    var presenter: TabbarReceptionistInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol TabbarReceptionistViewProtocol: class {

    var presenter: TabbarReceptionistPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
