//
//  ListReceiptProtocols.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol ListReceiptWireframeProtocol: class {

}
//MARK: Presenter -
protocol ListReceiptPresenterProtocol: class {

    var interactor: ListReceiptInteractorInputProtocol? { get set }
    func getInvoices(page: Int, pageSize: Int, invoiceType: Int, isInDay: Bool)
}

//MARK: Interactor -
protocol ListReceiptInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetInvoices(result: InvoiceResponse?, error: APIError?)
}

protocol ListReceiptInteractorInputProtocol: class {

    var presenter: ListReceiptInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getInvoices(page: Int, pageSize: Int, invoiceType: Int, isInDay: Bool)
}

//MARK: View -
protocol ListReceiptViewProtocol: class {

    var presenter: ListReceiptPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetInvoices(result: InvoiceResponse?, error: APIError?)
}
