//
//  ListReceiptViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/26/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class ListReceiptViewController: HomeBaseViewController {

	var presenter: ListReceiptPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func setUpNavigation() {
        setTitleNavigation(title: "Phiếu thu")
    }

}

extension ListReceiptViewController: ListReceiptViewProtocol {
	
}
