//
//  CreateNewReceiptViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CreateNewReceiptViewController: BaseViewController {

    @IBOutlet weak var vCustomerName: AppTextFieldLogo!
    @IBOutlet weak var vNote: AppTextFieldLogo!

    @IBOutlet weak var vService: ServiceView!

    @IBOutlet weak var lbEmployeeName: UILabel!
    @IBOutlet weak var lbCurrentTime: UILabel!

	var presenter: CreateNewReceiptPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func setUpNavigation() {
        addBackWhiteToNavigation()
        addButtonTextToNavigation(title: "Đồng ý", style: .right, action: #selector(btnAcceptTapped))
    }

    override func setUpViews() {
        vCustomerName.setTitleAndLogo(AppImage.imgUser, title: "Tên khách hàng")
        vCustomerName.setPlaceHolder(title: "Nhập tên khách hàng")
        vNote.setTitleAndLogo(AppImage.imgReceipts, title: "Ghi chú")
        vNote.setPlaceHolder(title: "Nhập ghi chú")
        vCustomerName.setHeightTitle(value: 20)
        vNote.setHeightTitle(value: 20)

        guard let user = UserDefaultHelper.shared.getUser() else { return }
        lbEmployeeName.text = "Nhân viên: \(user.Email&)"
        lbCurrentTime.text = "Thời gian: \(Date().toDateFormatCurrentTime(DateFormat.SIMPLE_DATE))"

        vService.addNewCallBack = {[weak self] (widget, total) in
            guard let self = self else { return }
//            self.listWidget.append((widget, total))
        }
    }


    @objc func btnAcceptTapped() {

    }
}

extension CreateNewReceiptViewController: CreateNewReceiptViewProtocol {
	
}

