//
//  CreateNewReceiptPresenter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CreateNewReceiptPresenter: CreateNewReceiptPresenterProtocol {
    func insertOrUpdateInvoice(param: InsertInvoiceParam) {
        interactor?.insertOrUpdateInvoice(param: param)
    }
    

    weak private var view: CreateNewReceiptViewProtocol?
    var interactor: CreateNewReceiptInteractorInputProtocol?
    private let router: CreateNewReceiptWireframeProtocol

    init(interface: CreateNewReceiptViewProtocol, interactor: CreateNewReceiptInteractorInputProtocol?, router: CreateNewReceiptWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension CreateNewReceiptPresenter: CreateNewReceiptInteractorOutputProtocol {
    func didInsertOrUpdateInvoice(result: BaseResponse?, error: APIError?) {
        view?.didInsertOrUpdateInvoice(result: result, error: error)
    }
    
	
}
