//
//  CreateNewReceiptRouter.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CreateNewReceiptRouter: CreateNewReceiptWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CreateNewReceiptViewController(nibName: nil, bundle: nil)
        let interactor = CreateNewReceiptInteractor()
        let router = CreateNewReceiptRouter()
        let presenter = CreateNewReceiptPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
