//
//  CreateNewReceiptInteractor.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CreateNewReceiptInteractor: CreateNewReceiptInteractorInputProtocol {
    func insertOrUpdateInvoice(param: InsertInvoiceParam) {
        Provider.shared.receptionistAPIService.insertOrUpdateInvoice(param: param, success: { (result) in
            self.presenter?.didInsertOrUpdateInvoice(result: result, error: nil)
        }) { (error) in
            self.presenter?.didInsertOrUpdateInvoice(result: nil, error: error)
        }
    }
    

    weak var presenter: CreateNewReceiptInteractorOutputProtocol?
}
