//
//  CreateNewReceiptViewController.swift
//  Bizkasa
//
//  Created DINH VAN TIEN on 2/29/20.
//  Copyright © 2020 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class CreateNewReceiptViewController: BaseViewController {

    @IBOutlet weak var vCustomerName: AppTextFieldLogo!
    @IBOutlet weak var vNote: AppTextFieldLogo!

    @IBOutlet weak var vService: ServiceView!

    @IBOutlet weak var lbEmployeeName: UILabel!
    @IBOutlet weak var lbCurrentTime: UILabel!

	var presenter: CreateNewReceiptPresenterProtocol?
    
    let param = InsertInvoiceParam()

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func setUpNavigation() {
        addBackWhiteToNavigation()
        addButtonTextToNavigation(title: "Đồng ý", style: .right, action: #selector(btnAcceptTapped))
    }

    override func setUpViews() {
        vCustomerName.setTitleAndLogo(AppImage.imgUser, title: "Tên khách hàng")
        vCustomerName.setPlaceHolder(title: "Nhập tên khách hàng")
        vNote.setTitleAndLogo(AppImage.imgReceipts, title: "Ghi chú")
        vNote.setPlaceHolder(title: "Nhập ghi chú")
        vCustomerName.setHeightTitle(value: 20)
        vNote.setHeightTitle(value: 20)

        guard let user = UserDefaultHelper.shared.getUser() else { return }
        lbEmployeeName.text = "Nhân viên: \(user.Email&)"
        lbCurrentTime.text = "Thời gian: \(Date().toDateFormatCurrentTime(DateFormat.SIMPLE_DATE))"

        vService.addNewCallBack = {[weak self] (widget, total) in
            guard self != nil else { return }
//            self.listWidget.append((widget, total))
            
        }
    }


    @objc func btnAcceptTapped() {
        param.CustomerName = vCustomerName.getText()
        param.Note = vNote.getText()
        param.invoiceDetails = vService.listWidget.map({$0.0})
        param.InvoiceStatus = 7
        param.InvoiceType = 1
        param.TotalAmount = vService.totalAmount
        param.Cashed = vService.totalAmount
        presenter?.insertOrUpdateInvoice(param: param)
    }
}

extension CreateNewReceiptViewController: CreateNewReceiptViewProtocol {
    func didInsertOrUpdateInvoice(result: BaseResponse?, error: APIError?) {
        if let _ = result {
            self.makeToast(message: "Thêm hoá đơn thành công!")
            NotificationCenter.default.post(name: .refreshReceptionist, object: nil)
            self.closePage()
        } else {
            self.makeToast(message: error?.message?.first ?? "")
        }
    }
}

